### ISSUE TITLE
International Day Event

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/denver-boulder#15]
Hello guys, @ralucas signed you up for the international day but it seems you havn't come around to setup an event site yet! See: https://github.com/nodeschool/international-day/issues/22

**Comment by iancrowther** [comment]
is this event still happening?

**Comment by iancrowther** [comment]
do you have photos/videos/logos from the event?

**Comment by ralucas** [comment]
Hi Ian,
We were unable to put this event on.  My apologies.  I hope you are able to make it to a future event.

Best,

Richard

**Comment by iancrowther** [comment]
np - was just checking
